# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-04-24 05:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='imports',
            fields=[
                ('import_country', models.CharField(max_length=30)),
                ('model', models.CharField(max_length=30)),
                ('make', models.CharField(max_length=30)),
                ('sold_by', models.CharField(max_length=50)),
                ('sale_price', models.CharField(max_length=10)),
            ],
        ),
    ]
