# Generated by Django 2.0.4 on 2018-05-01 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dataDisplay', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('import_country', models.CharField(max_length=30)),
                ('model', models.CharField(max_length=30)),
                ('make', models.CharField(max_length=30)),
                ('sold_by', models.CharField(max_length=50)),
                ('sale_price', models.CharField(max_length=10)),
            ],
        ),
        migrations.DeleteModel(
            name='imports',
        ),
    ]
